routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('lang/{lang}', 'HomeController@lang')->name('lang');


Route::get('/shop', function () {
    return view('shop');
})->name('shop');
Route::get('/timetable', function () {
    return view('timetable');
})->name('timetable');
Route::get('/all_doctors', function () {
    return view('all_doctors');
})->name('all_doctors');
Route::get('/blog', function () {
    return view('blog');
})->name('blog');
Route::get('/confirm/{id}/{token}', 'Auth\RegisterController@confirm');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'roles', 'roles' => ["ADMINISTRATOR", "UPDATE_USERS", "DELETE_USERS", "USERS_MANAGER", "BOARDS_MANAGER", "UPDATE_BOARDS", "DELETE_BOARDS"] ], function () {
    Route::get('boards', 'BoardsController@index')->name('admin.boards');
    Route::get('boards/show/{id}', 'BoardsController@show')->where('id', '[0-9]+');
    Route::put('boards/update', 'BoardsController@update');
    Route::get('boards/create', 'BoardsController@create');
    Route::delete('boards/destroy/{id}', 'BoardsController@destroy')->where('id', '[0-9]+');
    //users routes
    Route::get('users', 'UsersController@index')->name('admin.users');
    Route::get('users/view/{id}', 'UsersController@view');
    Route::put('users/update', 'UsersController@update');
    Route::get('users/create', 'UsersController@create');

    //users routes
    Route::get('posts/single/{id}', 'PostsController@single')->name('admin.posts.single')->where('id', '[0-9]+');

    Route::get('users/attempt/{id}', 'UsersController@attempt')->name('deputy');

    //cecam routes
    // Posts Routes
    Route::get('posts', 'PostsController@index')->name('admin.posts');
    Route::get('posts/show/{id}', 'PostsController@show')->where('id', '[0-9]+');
    Route::post('posts/view', 'PostsController@view');
    Route::put('posts/update', 'PostsController@update');



    //Categories Routes
    Route::get('categories/show', 'CategoriesController@show');
    Route::post('categories/view', 'CategoriesController@view');
    Route::get('categories/load/{search?}', 'CategoriesController@load');
    Route::put('categories/update', 'CategoriesController@update');

    // Notifications Routes
    Route::post('attachments/store', 'AttachmentsController@store');
    Route::post('posts/attachments', 'AttachmentsController@uploadFiles');
    Route::post('posts/attachments/upload', 'AttachmentsController@uploadDocuments');
    Route::delete('posts/attachments/delete/{post_id}/{user_id}/{attachment_id}', 'AttachmentsController@destroy')->where('post_id', '[0-9]+')->where('user_id', '[0-9]+')->where('attachment_id', '[0-9]+');
    Route::get('blog', function () {
        return view('admin.blog');
    })->name('admin.blog');

});
Route::group(['namespace' => 'Admin', 'middleware' => 'roles', 'roles' => ["ADMINISTRATOR", "UPDATE_USERS", "DELETE_USERS", "USERS_MANAGER", "BOARDS_MANAGER", "UPDATE_BOARDS", "DELETE_BOARDS"] ], function () {
    Route::get('pages', 'PagesController@index')->name('admin.pages');
    Route::get('pages/view/{id}', 'PagesController@view')->name('admin.pages.view');
    Route::put('pages/update', 'PagesController@update')->name('admin.pages.update');
    Route::post('pages/attachments', 'AttachmentsController@uploadFiles');
});
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'roles', 'roles' => ["DEPUTY"] ], function () {
    Route::get('users/attempt/{id}', 'UsersController@attempt')->name('deputy');
});
Route::group(['middleware' => 'roles', 'roles' => ["USER", "ADMINISTRATOR"] ], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::group(['namespace' => 'User', 'middleware' => 'roles', 'roles' => ["USER", "ADMINISTRATOR"]], function () {
    Route::get('profile', 'PagesController@profile')->name('profile');
    Route::put('users/update', 'UsersController@update');
    Route::get('notification', 'PagesController@notification')->name('notification');
    Route::get('tasks', 'PagesController@tasks')->name('tasks');
    Route::get('inbox', 'PagesController@inbox')->name('inbox');
    Route::get('locked', 'PagesController@locked')->name('locked');
    Route::get('calendar', 'PagesController@calendar')->name('calendar');
    Route::get('pricing', 'PagesController@pricing')->name('pricing');


    // comments Routes
    Route::get('comments/{id}/{type}', 'CommentsController@index')->name('comments');
    Route::post('comments/{post}', 'CommentsController@store');
    Route::delete('comments/destroy/{id}', 'CommentsController@destroy');
    Route::put('comments/edit/{id}', 'CommentsController@edit');

    // Posts Routes
    Route::get('posts', 'PostsController@index')->name('posts');
    Route::get('posts/show/{id}', 'PostsController@show')->where('id', '[0-9]+');
    Route::post('posts/view', 'PostsController@view');
    Route::put('posts/update', 'PostsController@update');

    //Categories Routes
    Route::get('categories/show', 'CategoriesController@show');
    Route::post('categories/view', 'CategoriesController@view');
    Route::get('categories/load/{search?}', 'CategoriesController@load');
    Route::put('categories/update', 'CategoriesController@update');

    // Notifications Routes
    Route::post('attachments/store', 'AttachmentsController@store');
    Route::post('posts/attachments', 'AttachmentsController@uploadFiles');
    Route::post('posts/attachments/upload', 'AttachmentsController@uploadDocuments');
    Route::delete('posts/attachments/delete/{post_id}/{user_id}/{attachment_id}', 'AttachmentsController@destroy')->where('post_id', '[0-9]+')->where('user_id', '[0-9]+')->where('attachment_id', '[0-9]+');

    Route::get('notifications/show/{id}', 'NotificationsController@show');

    // Kids Routes
    Route::get('kid', 'KidsController@kid')->name('kid');
    Route::get('kids/view', 'KidsController@view');
    Route::get('kids/show/{id}', 'KidsController@show')->where('id', '[0-9]+');



});







Route::get('/', function () {
    return view('welcome');
});


Route::group(['namespace' => 'User'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/about', 'PagesController@about')->name('about');
    Route::get('/contact', 'PagesController@contact')->name('contact');
    Route::get('/blog', 'PagesController@blog')->name('blog');
    Route::get('/culture', 'PagesController@culture')->name('culture');
    Route::get('/sport', 'PagesController@sport')->name('sport');
    Route::get('/tech', 'PagesController@tech')->name('tech');
    Route::get('/marketing', 'PagesController@marketing')->name('marketing');
    Route::get('/events', 'PagesController@events')->name('events');
    Route::get('/ethic', 'PagesController@ethic')->name('ethic');
    Route::get('/post', 'PagesController@post')->name('post');
    Route::get('/impressum', 'PagesController@impressum')->name('impressum');
});

app/Comment.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public $guarded = [];
    protected static $commentable_for = ['Post'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function commentable()
    {
        return $this->morphTo();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public static function allFor($model, $model_id)
    {
        $comments = [];
        $by_id = [];
        $records = self::where(['commentable_type' => $model, 'commentable_id' => $model_id])->orderBy('id', 'asc')->get();
        $records->load('user');
        foreach ($records as $record) {
            if ($record->reply) {
                $by_id[$record->reply]->attributes['replies'][] = $record;
            } else {
                $record->attributes['replies'] = [];
                $by_id[$record->id] = $record;
                $comments[] = $record;
            }
        }
        return array_reverse($comments);
    }

    public static function isCommentable($model, $model_id)
    {
        if (!in_array($model, self::$commentable_for)) {
            return false;
        } else {
            $model = "\\App\\$model";
            return $model::where(['id' => $model_id])->exists();
        }
    }

    /**
     * @param $date
     * @return mixed
     */
    public function getCreatedAtAttribute($date)
    {
        Carbon::setLocale(session('locale'));

        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }
}

resources/views/admin/boards.blade.php
@extends('layouts.default')

@section('title')
    <title>H4K | Boards Admin</title>
@endsection
@section('css')

@endsection
@section('js_before')
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/datatables.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/pdfmake/pdfmake.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/pdfmake/vfs_fonts.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/buttons.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/responsive.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/forms/selects/select2.min.js") }}"></script>
@endsection
@section('js_after')
    <script type="text/javascript" src="{{ asset("assets/js/pages/admin_boards.js") }}"></script>
    <script type="text/javascript" src="{{ asset("/js/admin/boards/boards.js") }}"></script>
@endsection

@section('breadcrumb')
    <ul class="breadcrumb">
        <li><a href="index.html"><i class="icon-home2 position-left"></i> Home</a></li>
        <li class="active"> @lang('menus.calendar')</li>
    </ul>
    @endsection
    @section('content')
    <div class="panel panel-flat" id="vueBoards">
        @include('admin/modal/boards_dlgs')
        <div class="panel-heading">
            <h6 class="panel-title">Boards Manager</h6>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
        </div>

        <table class="table table-striped text-nowrap table-customers">
            <thead>
            <tr>
                <th>id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Members</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Actions</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (json_decode($boards) as $board)
                <tr>
                    <td>{{ $board->id }}</td>
                    <td><a href="#" data-popup="tooltip" title="{{ $board->name }}">{{ $board->name  }}</a></td>
                    <td><a href="#" data-popup="tooltip" title="{{ $board->description }}">{{ $board->description  }}</a></td>
                    <td><a href="#" data-popup="tooltip" title="{{ $board->users_count }}">{{ $board->users_count  }}</a></td>
                    <td>{{ $board->created_at  }}</td>
                    <td>{{ $board->updated_at  }} </td>
                    <td class="text-right">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu7"></i>
                                    <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="javascript:;" @click="show({{ $board->id }})" data-popup="tooltip" title="Show"><i class="icon-eye4"></i> Show</a></li>
                                    <li class="divider"></li>
                                    <li><a href="javascript:;" @click="edit({{ $board->id }})" data-popup="tooltip" title="Edit"><i class="icon-pencil7"></i> Edit</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#" data-popup="tooltip" title="Delete"><i class="icon-trash"></i> Delete</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                    <td class="no-padding-left"></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /customers -->
@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('title')
    <title>H4K | Administration</title>
@endsection
@section('css')

@endsection
@section('js_before')
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/datatables.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/responsive.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/forms/selects/select2.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/jszip/jszip.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/pdfmake/pdfmake.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/pdfmake/vfs_fonts.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/tables/datatables/extensions/buttons.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/plugins/forms/selects/bootstrap_select.min.js") }}"></script>
@endsection
@section('js_after')
    <script type="text/javascript" src="{{ asset("assets/js/pages/components_notifications_pnotify.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/pages/datatables_extension_buttons_html5.js") }}"></script>
    <script type="text/javascript" src="{{ asset("assets/js/pages/users_customers.js") }}"></script>
    <script type="text/javascript" src="{{ asset("/js/admin/users/users.js") }}"></script>
@endsection
@section('breadcrumb')
    <ul class="breadcrumb">
        <li><a href="index.html"><i class="icon-home2 position-left"></i> Home</a></li>
        <li><a href="user_profile_tabbed.html">Admin</a></li>
        <li class="active">Users</li>
    </ul>
@endsection
@section('content')
    <div id="vueUsers" class="row">
        @include('admin/modal/users_dlgs')
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">@lang('tables.user_manager')</h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        @if($permitted["create"])
                        <li><a @click="create" data-popup="tooltip" title="Add"><i class="icon-plus3"></i> </a></li>
                        @endif
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <div class="panel-body">

            </div>

            <table class="table datatable-responsive-column-controlled">
                <thead>
                <tr>
                    <th></th>
                    <th>id</th>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Telephone</th>
                    <th>Adresse</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (json_decode($users) as $user)
                    <tr class="context-dynamic" data-id="{{ $user->id }}">
                        <td></td>
                        <td><h6 class="no-margin text-semibold">{{ $user->id }}</h6></td>
                        <td>
                            <div class="media">
                                <a href="user_pages_profile_tabbed.html" class="media-left">
                                    <img src="{{ asset("assets/images/placeholder.jpg")}}" width="40" height="40" class="img-circle img-md" alt="">
                                </a>

                                <div class="media-body media-middle">
                                    <a @click="view({{ $user->id }})" data-popup="tooltip" title="{{ $user->full_name }}" class="text-semibold">{{ $user->full_name }}</a>
                                    <div class="text-muted text-size-small">
                                        Date d'enregistrement: {{ $user->created_at }}
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td><a @click="view({{ $user->id }})" data-popup="tooltip" title="{{ $user->username }}">{{ $user->username }}</a></td>
                        <td><a @click="view({{ $user->id }})" data-popup="tooltip" title="{{ $user->email }}" >{{ $user->email }}</a></td>
                        <td> <span data-popup="tooltip" title="{{ $user->phone1 }}" role="button" >{{ $user->phone1 }}</span></td>
                        <td>
                            <ul class="list list-unstyled no-margin">
                                <li class="no-margin">
                                    <i class="icon-location3 text-size-base text-warning position-left"></i>
                                    Pays:
                                    <a href="javascript:;" data-popup="tooltip" title="{{ $user->country }}">{{ $user->country }}</a>
                                </li>

                                <li class="no-margin">
                                    <i class="icon-location4 text-size-base text-success position-left"></i>
                                    Ville:
                                    <a href="javascript:;" data-popup="tooltip" title="{{ $user->city }}">{{ $user->city }}</a>
                                </li>
                            </ul>
                        </td>
                        <td class="text-center">
                            <ul class="icons-list">
                                <li><a @click="view({{ $user->id }})" data-popup="tooltip" title="Show"><i class="icon-eye4"></i></a></li>
                                @if($permitted["update"])
                                <li><a @click="edit({{ $user->id }})" data-popup="tooltip" title="Edit"><i class="icon-pencil7"></i></a></li>
                                @endif
                                @if($permitted["delete"])
                                <li><a @click="destroy({{ $user->id }})" data-popup="tooltip" title="Delete"><i class="icon-trash"></i></a></li>
                                @endif
                                @if($permitted["login"])
                                <li><a href="{{ route('deputy', $user->id ) }}" data-popup="tooltip" title="Sign in"><i class="icon-user-check"></i></a></li>
                                @endif
                            </ul>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="context-dynamic-menu">
                <ul class="dropdown-menu">
                    @if($permitted["create"])
                        <li><a href="javascript:;"><i class="icon-user-plus"></i> Add</a></li>
                    @endif
                    <li><a href="javascript:;"><i class="icon-eye4"></i> Show</a></li>
                    @if($permitted["update"])
                    <li><a href="javascript:;"><i class="icon-pencil6"></i> Edit</a></li>
                    @endif
                    @if($permitted["delete"])
                    <li><a href="javascript:;"><i class="icon-trash"></i> Delete</a></li>
                    @endif
                    @if($permitted["login"])
                    <li><a href="{{ route('deputy', $user->id ) }}"><i class="icon-user-check"></i> Login</a></li>
                    @endif
                </ul>
            </div>

        </div>
    </div>



@endsection